
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alertmanager-main
  namespace: monitoring
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged
  verbs:
  - use
